### ISSUE TITLE
object like arguments in nodejs

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#3]
https://github.com/vtrofin/takezo/blob/3e4da34b009fadd390f3ed998d2adfea096b57d7/store.js#L10-L33

I am getting the following error TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView  when passing saltHashPassword an object like argument. 

Why is that? The function works properly if I pass two strings as arguments.

**Comment by martinheidegger** [comment]
Please, provide a stacktrace

**Comment by vtrofin** [comment]
Here is a printscreen https://gyazo.com/5dcfcbb6902350a3315410d64b00d6dd

**Comment by martinheidegger** [comment]
No printscreen! The error message as text, the stacktrace [collapsible](https://github.com/dear-github/dear-github/issues/166#issuecomment-2363422099. Private data such as "user home directory" removed.

**Comment by vtrofin** [comment]
<details>
  <summary>TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView</summary>
      at Hmac.update (internal/crypto/hash.js:53:11)
    at saltHashPassword (.../takezo/initStore.js:11:4)
    at Object.createUser (.../takezo/initStore.js:24:25)
    at server.post (.../takezo/server.js:105:9)
    at Layer.handle [as handle_request] (.../takezo/node_modules/express/lib/router/layer.js:95:5)
    at next (.../takezo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (.../takezo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (.../takezo/node_modules/express/lib/router/layer.js:95:5)
    at .../takezo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (.../takezo/node_modules/express/lib/router/index.js:335:12)
    at next (.../takezo/node_modules/express/lib/router/index.js:275:10)
    at .../takezo/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (.../takezo/node_modules/raw-body/index.js:224:16)
    at done (.../takezo/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (.../takezo/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:159:13)
</details>

**Comment by martinheidegger** [comment]
[`crypto.createHmac(algorithm, key[, options])`](https://nodejs.org/api/crypto.html#crypto_crypto_createhmac_algorithm_key_options) requires - as is written in the error - `string`, `TypedArray`, or `DataView` as a key (aka. salt). If you look at `saltWithPassword`:

```javascript
saltHashPassword = ({ string, salt = randomString() }) => { ...
```

then you can assume that you need to call it with an object looking like this:

```javascript
saltHashPassword({
  string: 'text', // required!
  salt: 'something', // not required!
})
```

yet you are calling it like this:

https://github.com/vtrofin/takezo/blob/3e4da34b009fadd390f3ed998d2adfea096b57d7/store.js#L23

Where you pass the object:

```javascript
{ password }
```
which becomes:

```javascript
{
  password: password
}
```

where is the `string` property?
