### ISSUE TITLE
GraphQL server - TypeError: resolver is not a function

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#5]
<pre>TypeError: loaders.getNodeById is not a function\n</pre>
<details>
  <pre>
at resolve (/Users/vtrofin/Victor/Github/takezo/server.js:56:21)\n    
at resolveFieldValueOrError (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:544:18)\n
at resolveField (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:508:16)\n    
at /Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:357:18\n    
at Array.reduce (<anonymous>)\n    
at executeFields (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:354:42)\n    
at executeOperation (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:278:122)\n    
at executeImpl (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:142:14)\n    
at execute (/Users/vtrofin/Victor/Github/takezo/node_modules/graphql/execution/execute.js:119:229)\n    
at /Users/vtrofin/Victor/Github/takezo/node_modules/express-graphql/dist/index.js:164:37\n    
at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
  </pre>
</details>

The code looks like this:  
1. the RootQuery https://github.com/vtrofin/takezo/blob/a32eae69eff0f3d0019eb2f7da15859d48870dbc/server.js#L35-L61
2. the getNodeById function 
https://github.com/vtrofin/takezo/blob/a32eae69eff0f3d0019eb2f7da15859d48870dbc/ql/loaders.js#L3-L22
3. the splitNodeId function
https://github.com/vtrofin/takezo/blob/a32eae69eff0f3d0019eb2f7da15859d48870dbc/ql/qlhelpers.js#L1-L14

I've checked the query in the function. it returns a proper result in the form of an array of objects [{id: ...}] when run separately.

**Comment by martinheidegger** [comment]
Okay: The title of the issue _"TypeError: resolver is not a function"_ is not the same as  _"TypeError: loaders.getNodeById is not a function"_

**Comment by martinheidegger** [comment]
`loaders` as defined here: https://github.com/vtrofin/takezo/blob/a32eae69eff0f3d0019eb2f7da15859d48870dbc/server.js#L28 is a function with a `(db) => {}` signature (that is never called)
